import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import StyledComponentsRegistry from "@/lib/registry";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
